trigger:
  branches:
    include:
      - azure-pipelines

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: chess-stats-dev-variable-group
  - name: ImageNameBase
    value: 'chessstats.azurecr.io/chess-stats-dev'
  - name: Environment
    value: chess-stats-dev
  - name: BranchName
    value: azure-pipelines


steps:
  - task: CmdLine@2
    displayName: Generate Commit Short SHA
    inputs:
      script: ' x=`echo "$(Build.SourceVersion)" | head -c 7`; echo "##vso[task.setvariable variable=ShortSha]$x"'

  - task: Docker@2
    displayName: Build an image
    inputs:
      command: build
      containerRegistry: chessstats
      repository: $(Environment)/$(BranchName)
      arguments: '--build-arg APP_INSIGHTS_KEY=$(APP-INSIGHTS-KEY) --build-arg APP_VERSION=$(BranchName)--$(ShortSha)'
      tags: |
        $(BranchName)--$(ShortSha)
        latest

  - task: Docker@2
    displayName: Push an image
    inputs:
      containerRegistry: chessstats
      repository: $(Environment)/$(BranchName)
      command: push
      tags: |
        $(BranchName)--$(ShortSha)
        latest
