trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: chess-stats-dev-variable-group

extends:
  template: ./templates/build-and-push-to-registry.yml
  parameters:
      AppInsightsKey: $(APP-INSIGHTS-KEY)
      BranchName: develop
      Environment: chess-stats-dev
