
name: Build & Push to Dev - Azure
on:
  push:
    branches:
      - develop
      - devops/azure

jobs:
  build-and-push-to-azure:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - id: image-tag
      uses: n8rzz/chess-stats/.github/actions/build-tag@develop

    - name: 'Login via Azure CLI'
      if: ${{ contains(github.ref, 'develop') || contains(github.ref, 'devops/azure')}}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - uses: azure/docker-login@v1
      env:
        APP_INSIGHTS_INSURMENTATION_KEY: ${{ secrets.NEXT_PUBLIC_APPINSIGHTS_INSTRUMENTATION_KEY_DEV }}
      with:
        login-server: chessstats.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build \
          -t chessstats.azurecr.io/chess-stats-dev/${GITHUB_REF##*/}/${{ steps.image-tag.outputs.image-tag }} \
          -t chessstats.azurecr.io/chess-stats-dev/develop:latest \
          --build-arg APP_INSIGHTS_KEY=$APP_INSIGHTS_INSURMENTATION_KEY \
          .
        docker push chessstats.azurecr.io/chess-stats-dev/${GITHUB_REF##*/}/${{ steps.image-tag.outputs.image-tag }}
        docker push chessstats.azurecr.io/chess-stats-dev/develop:latest
